name: "test create issues"
description: "test create issues"
# inputs:
# who-to-greet: # id of input
#   description: "Who to greet"
#   required: true
#   default: "World"
runs:
  using: "node12"
  main: "dist/index.js"
