on: [push]

jobs:
  create_issues_action:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      - name: create issues action
        uses: ./ # Uses an action in the root directory
        # with:
        #   who-to-greet: "Mona the Octocat"
